version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1323:1323"
    command: 
      - air
    volumes:
      - ./:/go/src/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: household_account_book
      MYSQL_USER: app-user
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
